services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    init: true
    restart: always
    volumes:
      - ~/dockermount/opencms-docker-mysql:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=secretDBpassword"
  opencms:
    image: sagasoluciones/opencms-tomcat:${OPENCMS_VERSION:-21.0.1}
    container_name: opencms
    build:
      context: ./image-21
      args:
        SERVLET_CONTAINER: tomcat
        BASE_IMAGE: tomcat:9.0-jdk21
        OPENCMS_VERSION: ${OPENCMS_VERSION:-21.0.1}
        OPENCMS_VERSION_TAG: ${OPENCMS_VERSION_TAG:-build_21_0_1}
    init: true
    restart: always
    depends_on: [ "mariadb" ]
    links:
      - "mariadb:mysql"
    ports:
      - "80:8080"
    volumes:
      - ~/dockermount/opencms-docker-webapps:/container/webapps
    command: [ "/root/wait-for.sh", "mysql:3306", "-t", "30", "--", "/root/opencms-run.sh" ]
    environment:
      - "DB_PASSWD=secretDBpassword"
